apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: dind
spec:
  containers:
    - name: shell
      image: docker:20.10.24-dind
      command:
        - sh
        - -c
        - |
          apk add --no-cache git bash openssh-client && \
          dockerd-entrypoint.sh & \
          sleep infinity
      tty: true
      securityContent:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_HOST
          value: "unix:///var/run/docker.sock"
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
        - name: known-hosts
          mountPath: /root/.ssh
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
    - name: known-hosts
      emptyDir: {}